spring:
  application:
    name: customer-service
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username:  montisangwan
    password:  Sirion@123
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
